// Auto-generated by refactor script
import React from "react";
import BiggiButton from "./BiggiButton.jsx";
const Button = ({ variant = "ghost", children, ...props }) => (
  <BiggiButton variant={variant} {...props}>
    {children}
  </BiggiButton>
);
export default Button;

