import {
  formatAmountDisplay,
  formatNativeDisplay,
  formatTokenDisplay,
  toDisplayNumber,
} from "./amountFormatting.js";

// Auto-generated by refactor script
export const fmtVal = (val, symbol = "", decimals = 2) => {
  if (val == null) return "--";
  if (symbol === "POL" || symbol === "MATIC") {
    return formatNativeDisplay(val, decimals);
  }
  if (symbol === "BIGGI") {
    return formatTokenDisplay(val, 18, decimals);
  }
  return formatAmountDisplay(val, {
    unit: symbol,
    maximumFractionDigits: decimals,
  });
};

export const withTimeout = (promiseOrFn, ms, label) => {
  return new Promise((resolve) => {
    const safetyTimer = setTimeout(() => {
      console.warn(
        `[withTimeout] ${label || "task"} force-resolved after ${ms}ms`,
      );
      resolve(null);
    }, ms);
    const finish = (val) => {
      clearTimeout(safetyTimer);
      resolve(val);
    };
    if (promiseOrFn == null) {
      finish(null);
      return;
    }
    let result;
    try {
      result = typeof promiseOrFn === "function" ? promiseOrFn() : promiseOrFn;
    } catch (err) {
      console.warn(
        `[withTimeout] ${label || "task"} threw on call:`,
        err?.message || err,
      );
      finish(null);
      return;
    }
    if (result == null || typeof result.then !== "function") {
      finish(result);
      return;
    }
    result.then(
      (val) => finish(val),
      (err) => {
        console.warn(
          `[withTimeout] ${label || "task"} rejected:`,
          err?.message || err,
        );
        finish(null);
      },
    );
  });
};

export const numFrom = (value) => {
  return toDisplayNumber(value);
};

export const shortAddr = (addr) => {
  if (!addr) return "--";
  return `${addr.slice(0, 6)}...${addr.slice(-4)}`;
};

export const isAddress = (addr) =>
  typeof addr === "string" && /^0x[0-9a-fA-F]{40}$/.test(addr);

// Default explorer is Polygon mainnet. Move this to a network-aware helper when multi-chain support is needed.
export const explorerLink = (addr) =>
  addr ? `https://polygonscan.com/address/${addr}` : null;

export const fmtLp = (val) => {
  if (val == null) return "--";
  return formatAmountDisplay(val, {
    decimals: 18,
    unit: "LP",
    maximumFractionDigits: 4,
  });
};

export const fmtDate = (timestamp) => {
  if (!timestamp) return "--";
  const date = new Date(Number(timestamp) * 1000);
  return date.toLocaleString();
};
