// Skript pro rozdělení BiggiToken.jsx do modulární struktury
// Spouštějte v rootu projektu pomocí: node scripts/refactor_biggitoken.cjs

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '../src/panels/BiggiToken/BiggiToken.jsx');
const DEST = path.join(__dirname, '../src/panels/BiggiToken/');

// Mapování bloků na nové soubory
const blocks = [
  { name: 'components/Card.jsx', regex: /const Card = ([\s\S]*?return \([\s\S]*?\);\n\};)/ },
  { name: 'components/Line.jsx', regex: /const Line = ([\s\S]*?return \([\s\S]*?\);\n\};)/ },
  { name: 'components/AddressLine.jsx', regex: /const AddressLine = ([\s\S]*?return \([\s\S]*?\);\n\};)/ },
  { name: 'components/HeroStat.jsx', regex: /const HeroStat = ([\s\S]*?return \([\s\S]*?\);\n\};)/ },
  { name: 'components/BiggiButton.jsx', regex: /const BiggiButton = ([\s\S]*?return \([\s\S]*?\);\n\};)/ },
  { name: 'EcosystemErrorBoundary.jsx', regex: /class EcosystemErrorBoundary ([\s\S]*?\n\})/ },
  { name: 'utils/withTimeout.js', regex: /const withTimeout = ([\s\S]*?\n\};)/ },
  { name: 'utils/format.js', regex: /const fmtVal = ([\s\S]*?\n\};)/ },
  // ...další bloky podle potřeby
];

const code = fs.readFileSync(SRC, 'utf8');

blocks.forEach(({ name, regex }) => {
  const match = code.match(regex);
  if (match) {
    const outPath = path.join(DEST, name);
    fs.writeFileSync(outPath, `// Auto-generated by refactor script\n${match[0]}\n`);
    console.log(`Vytvořen: ${outPath}`);
  } else {
    console.warn(`Nenalezen blok pro ${name}`);
  }
});

console.log('Hotovo. Zkontrolujte nové soubory a opravte importy v BiggiTokenInner.jsx.');
