// Auto-generated by refactor script
const withTimeout = (promiseOrFn, ms, label) => {
  return new Promise((resolve) => {
    // Safety timeout - will ALWAYS resolve
    const safetyTimer = setTimeout(() => {
      console.warn(`[withTimeout] ${label || 'task'} force-resolved after ${ms}ms`);
      resolve(null);
    }, ms);

    const finish = (val) => {
      clearTimeout(safetyTimer);
      resolve(val);
    };

    // Handle undefined/null - return immediately
    if (promiseOrFn == null) {
      finish(null);
      return;
    }

    // If it's a function, call it
    let result;
    try {
      result = typeof promiseOrFn === 'function' ? promiseOrFn() : promiseOrFn;
    } catch (err) {
      console.warn(`[withTimeout] ${label || 'task'} threw on call:`, err?.message || err);
      finish(null);
      return;
    }

    // If not promise-like, return immediately
    if (result == null || typeof result.then !== 'function') {
      finish(result);
      return;
    }

    // Wait for promise
    result.then(
      (val) => finish(val),
      (err) => {
        console.warn(`[withTimeout] ${label || 'task'} rejected:`, err?.message || err);
        finish(null);
      }
    );
  });
};

export default withTimeout;

