// Auto-generated by refactor script
class EcosystemErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error) {
    return { hasError: true, error };
  }

  componentDidCatch(error, info) {
    console.error("BiggiToken panel crashed", error, info);
  }

  render() {
    if (this.state.hasError) {
      return (
        <section className="rewards-grid biggi-skin" style={{ padding: "24px" }}>
          <div className="rewards-grid__surface biggi-token-surface">
            <header className="rewards-grid__header biggi-header panel-header panel-header--ecosystem">
              <div className="rewards-grid__headline">
                <h2 className="rewards-grid__title">BIGGI ECOSYSTEM</h2>
                <p className="rewards-grid__subtitle">Panel spadl na chybe. Zkuste refresh nebo overit RPC.</p>
              </div>
            </header>
            <div className="flow-panel-box" style={{ color: "#f2c94c" }}>
              <p>Detail: {this.state.error?.message || String(this.state.error)}</p>
              <button className="tab-button" onClick={() => window.location.reload()}>Reload stranky</button>
            </div>
          </div>
        </section>
      );
    }
    return this.props.children;
  }
}

export default EcosystemErrorBoundary;

